### ISSUE TITLE
Add option to generate the graph only for selected module

### ISSUE THREAD

**Issue by mkutlev** [savvasdalkitsis/module-dependency-graph#5]
For projects with many modules and not well organized dependencies the generated image is hard to understand. It has a lot of arrows.

To be able to analyze and improve one module add a way to generate image only for the module and its dependencies.

**Example**
I want to generate graph image for login module. I would like to be able to do something like:
    - `./gradlew :features:login:graphModules`
    - `./gradlew graphModules -Pmodule=:features:login`

**Comment by mkutlev** [comment]
@savvasdalkitsis I just tried the new version. When I add the module to filter I see only its direct dependencies. It would be nice to be able to see the whole tree.

Example:
```
app
+--- :libraries:network:core
|    +--- :libraries:inject:core 
|    |    +--- :tracking
|    +--- :libraries:session
+--- :presentation:common
```

With the latest version when I use `-PgraphFilter=libraries:network:core` I would see only this:
```
:libraries:network:core
+--- :libraries:inject:core
+--- :libraries:session
```

I would expect this: 
```
:libraries:network:core
+--- :libraries:inject:core 
|    +--- :tracking
+--- :libraries:session
```

**Comment by savvasdalkitsis** [comment]
Hm yea i see your point. that is definitely doable but will take a bit of time to implement as i would have to generate the dep tree in memory myself so i can trim the nodes that are irrelevant. The current implementation lets graphviz handle the tree and all the plugin does is list all node relationships.

On the other hand, the fact that a dependency has another transient dependency shouldn't have a big effect on trying to isolate a module since, unless the transient dependency is marked as api, it should have no effect at compile time. 

If it is marked as api then it will definitely be useful to have the whole tree.

I will spend some time later this week to see if i can add this as an option
